spring:
  application:
    name: calculadoraacv

  datasource:
    url: jdbc:postgresql://localhost:55433/calculadora_acv
    username: calculadora_user
    password: calculadora_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false

  security:
    oauth2:
      client:
        registration:
          govbr:
            client-id: ${GOVBR_CLIENT_ID:seu-client-id}
            client-secret: ${GOVBR_CLIENT_SECRET:seu-client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - email
              - profile
              - govbr_confiabilidades
            client-authentication-method: client_secret_post
            client-name: Gov.br
        provider:
          govbr:
            # URLs de staging para desenvolvimento
            authorization-uri: https://sso.staging.acesso.gov.br/authorize
            token-uri: https://sso.staging.acesso.gov.br/token
            user-info-uri: https://sso.staging.acesso.gov.br/userinfo
            jwk-set-uri: https://sso.staging.acesso.gov.br/jwk
            user-name-attribute: sub
            user-info-authentication-method: header

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: NON_NULL

  validation:
    mode: fail-fast

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /calculadoraacv/backend
    session:
      timeout: 50m
      cookie:
        http-only: true
        secure: false
        same-site: lax
  error:
    include-stacktrace: never
    include-message: always

logging:
  level:
    '[br.gov.calculadoraacv]': DEBUG
    '[br.gov.serpro.calculadoraacv.config.RequestDebuggingFilter]': DEBUG
    '[org.springframework.security]': DEBUG
    '[org.springframework.security.oauth2]': DEBUG
    '[org.springframework.web]': DEBUG
    '[org.springframework.web.cors]': DEBUG
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE
    # Frontend tracking
    '[org.springframework.web.servlet.DispatcherServlet]': DEBUG
    '[org.springframework.web.servlet.mvc]': DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{requestId}] [%X{debugRequestId}] %logger{36} - %msg [%X{duracaoEmMilissegundos}ms]%n"

springdoc:
  api-docs:
    enabled: true
    path: /public/v3/api-docs
  swagger-ui:
    path: /public/swagger-ui.html
    config-url: /public/v3/api-docs/swagger-config
    urls-primary-name: calculadoraacv
    disable-swagger-default-url: true
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

management:
  endpoints:
    web:
      base-path: /public/actuator
      exposure:
        include: health,metrics,prometheus,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when-authorized
      show-components: always
    info:
      access: unrestricted
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:4200
      - http://localhost:8080
      - https://localhost:3000
      - https://localhost:4200
      - https://localhost:8080
      - https://des-calculadora-acv.np.bsa.estaleiro.serpro.gov.br
      - https://tes-calculadora-acv.np.bsa.estaleiro.serpro.gov.br
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

  oauth2:
    enabled: false  # Adicione esta linha para desabilitar OAuth2
    success-redirect-url: ${FRONTEND_URL:http://localhost:4200}/dashboard
    failure-redirect-url: ${FRONTEND_URL:http://localhost:4200}/login?error=oauth_failure
    post-logout-redirect-uri: ${FRONTEND_URL:http://localhost:4200}/login?logout=success
    
  govbr:
    staging:
      authorization-url: https://sso.staging.acesso.gov.br/authorize
      token-url: https://sso.staging.acesso.gov.br/token
      userinfo-url: https://sso.staging.acesso.gov.br/userinfo
      logout-url: https://sso.staging.acesso.gov.br/logout
      jwk-url: https://sso.staging.acesso.gov.br/jwk